### ISSUE TITLE
cmd problem

### ISSUE THREAD

**Issue by siddharthchandurkar** [AlizerUncaged/desktop-waifu#10]
Traceback (most recent call last):
  File "D:\new_cs_project\desktop-waifu-master\waifu\Src\runner.py", line 147, in <module>
    utils.characterAi.send_message_to_process_via_websocket(transcript)
  File "D:\new_cs_project\desktop-waifu-master\waifu\Src\utils\characterAi.py", line 31, in send_message_to_process_via_websocket
    ws.send(message)
  File "D:\new_cs_project\desktop-waifu-master\waifu\lib\site-packages\websocket\_app.py", line 240, in send
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
node js
Press any key to continue . . .

**Comment by siddharthchandurkar** [comment]
can anyone provide a solution on why this is happening
it records my voice but it dosent respond back

**Comment by NeoStormm** [comment]
Hey I have the same issue,  what dependency? and Is there another api that we used other then openai api key?

**Comment by Sylensar** [comment]
@mryansulbi ever got it working?
