### ISSUE TITLE
error when after using mic to try and talk

### ISSUE THREAD

**Issue by ihaveaskimask** [AlizerUncaged/desktop-waifu#101]
You (mic) > Hello?
Traceback (most recent call last):
  File "F:\Programs\AI\desktop-waifu-master\waifu\Src\runner.py", line 147, in <module>
    utils.characterAi.send_message_to_process_via_websocket(transcript)
  File "F:\Programs\AI\desktop-waifu-master\waifu\Src\utils\characterAi.py", line 31, in send_message_to_process_via_websocket
    ws.send(message)
AttributeError: 'NoneType' object has no attribute 'send'

**Comment by Luther-131** [comment]
I have the same error. Did you manage to find a solution or did you give up?

**Comment by ihaveaskimask** [comment]
Unfortunately not I was hoping maybe someone would be able to help through here thoughm

**Comment by Luther-131** [comment]
I see, well maybe in a little more time someone will find a solution.

Something that maybe I should mention. The error that I was getting is identical and at the end it says something about node js so I installed it, and for some reason it gives me a different error.

**Comment by Ivonchixd** [comment]
Im also having the same problem... :/

**Comment by MiMalhaar** [comment]
please share solution

**Comment by JPyle** [comment]
anyone figure it out ?
