### ISSUE TITLE
Microphone

### ISSUE THREAD

**Issue by Dayer69** [AlizerUncaged/desktop-waifu#115]
So i got VTube Studio and my sound settings picking up my mic. However the start.bat file does not and that is even after i press allow for the AP and i press RIGHT Control Key so right now i am at loss for what to do.

Here is the code if that helps:

←[1m←[32m
You are in a virtual environment: "D:\AI Waifu\waifu"
←[0m
Exception in thread Thread-1 (<lambda>):
Traceback (most recent call last):
  File "D:\Anaconda\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\Anaconda\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\AI Waifu\waifu\Src\utils\characterAi.py", line 85, in <lambda>
    t = threading.Thread(target=lambda: loop.run_until_complete(start()))
  File "D:\Anaconda\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\AI Waifu\waifu\Src\utils\characterAi.py", line 58, in start
    process = await asyncio.create_subprocess_exec(
  File "D:\Anaconda\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "D:\Anaconda\lib\asyncio\base_events.py", line 1675, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "D:\Anaconda\lib\asyncio\windows_events.py", line 394, in _make_subprocess_transport
    transp = _WindowsSubprocessTransport(self, protocol, args, shell,
  File "D:\Anaconda\lib\asyncio\base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "D:\Anaconda\lib\asyncio\windows_events.py", line 896, in _start
    self._proc = windows_utils.Popen(
  File "D:\Anaconda\lib\asyncio\windows_utils.py", line 153, in __init__
    super().__init__(args, stdin=stdin_rfd, stdout=stdout_wfd,
  File "D:\Anaconda\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Anaconda\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Welcome back, to speak press RIGHT_CTRL.
Connecting to VTube Studio!
You (mic) >Authentication request sent to VTube Studio, please click allow.
VTube Studio connected! at port 8001

**Comment by Siluuu** [comment]
i have the same issue
