### ISSUE TITLE
Microphone

### ISSUE THREAD

**Issue by TheOrdinaryDino1** [AlizerUncaged/desktop-waifu#117]
Traceback (most recent call last):
  File "C:\Waifu\desktop-waifu-master\waifu\Src\runner.py", line 147, in <module>
    utils.characterAi.send_message_to_process_via_websocket(transcript)
  File "C:\Waifu\desktop-waifu-master\waifu\Src\utils\characterAi.py", line 31, in send_message_to_process_via_websocket
    ws.send(message)
AttributeError: 'NoneType' object has no attribute 'send'
node js

**Comment by TheOrdinaryDino1** [comment]
ok i found the error, so basically just download node.js 18.16.1 from nodejs.org and it worked for me ig

**Comment by TheOrdinaryDino1** [comment]
now it says "node js: (text)
