### ISSUE TITLE
Index Error Issue

### ISSUE THREAD

**Issue by DarkMysticFox** [AlizerUncaged/desktop-waifu#156]
You are in a virtual environment: "C:\Waifu AI\desktop-waifu-master\waifu"

Traceback (most recent call last):
  File "C:\Waifu AI\desktop-waifu-master\waifu\Src\runner.py", line 60, in <module>
    import utils.elevenlabs
  File "C:\Waifu AI\desktop-waifu-master\waifu\Src\utils\elevenlabs.py", line 13, in <module>
    ELEVENLABS_VOICE = ELEVENLABS_CLIENT.get_voices_by_name(env_voice)[0]
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
node js
Press any key to continue . . .


Can Anyone tell me how to fix the index Error?

**Comment by ChrisDstryder** [comment]
I have the same problem as you. Did you manage to find a solution? How can I fix it?
