### ISSUE TITLE
Sending Transcription Error

### ISSUE THREAD

**Issue by PleaseHelpItsBroken** [AlizerUncaged/desktop-waifu#164]
Ima just copy the whole thing and yall tell me how to fix it

`←[1m←[32m                                                                                                                                                                   You are in a virtual environment: "C:\Users\ass\Desktop\pls\waifu"                                                                                                         ←[0m                                                                                                                                                                        C:\Users\ass\Desktop\pls\waifu\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work                 warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)                                                                           Exception in thread Thread-4 (<lambda>):                                                                                                                                    voicevox: 2023-07-31T11:16:24.524299Z  INFO voicevox_core::publish: 検出されたGPU (DirectMLには1番目のGPUが使われます):                                                     Traceback (most recent call last):                                                                                                                                            File "C:\Python310\lib\threading.py", line 1009, in _bootstrap_inner                                                                                                      voicevox: 2023-07-31T11:16:24.530895Z  INFO voicevox_core::publish:   - "Intel(R) HD Graphics 620" (128 MiB)                                                                voicevox: 2023-07-31T11:16:24.530935Z  INFO voicevox_core::publish:   - "Microsoft Basic Render Driver" (0 B)                                                                   self.run()                                                                                                                                                                File "C:\Python310\lib\threading.py", line 946, in run                                                                                                                        self._target(*self._args, **self._kwargs)                                                                                                                                 File "C:\Users\ass\Desktop\pls\waifu\Src\utils\characterAi.py", line 85, in <lambda>                                                                                         t = threading.Thread(target=lambda: loop.run_until_complete(start()))                                                                                                     File "C:\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete                                                                                               return future.result()                                                                                                                                                    File "C:\Users\ass\Desktop\pls\waifu\Src\utils\characterAi.py", line 58, in start                                                                                            process = await asyncio.create_subprocess_exec(                                                                                                                           File "C:\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec                                                                                            transport, protocol = await loop.subprocess_exec(                                                                                                                         File "C:\Python310\lib\asyncio\base_events.py", line 1652, in subprocess_exec                                                                                                 transport = await self._make_subprocess_transport(                                                                                                                        File "C:\Python310\lib\asyncio\windows_events.py", line 389, in _make_subprocess_transport                                                                                    transp = _WindowsSubprocessTransport(self, protocol, args, shell,                                                                                                         File "C:\Python310\lib\asyncio\base_subprocess.py", line 36, in __init__                                                                                                      self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,                                                                                                           File "C:\Python310\lib\asyncio\windows_events.py", line 885, in _start                                                                                                        self._proc = windows_utils.Popen(                                                                                                                                         File "C:\Python310\lib\asyncio\windows_utils.py", line 153, in __init__                                                                                                       super().__init__(args, stdin=stdin_rfd, stdout=stdout_wfd,                                                                                                                File "C:\Python310\lib\subprocess.py", line 966, in __init__                                                                                                                  self._execute_child(args, executable, preexec_fn, close_fds,                                                                                                              File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child                                                                                                           hp, ht, pid, tid = _winapi.CreateProcess(executable, args,                                                                                                              FileNotFoundError: [WinError 2] The system cannot find the file specified                                                                                                   voicevox: Warning: cpu_num_threads is set to 0. ( The library leaves the decision to the synthesis runtime )                                                                voicevox: INFO:     Started server process [1492]                                                                                                                           voicevox: INFO:     Waiting for application startup.                                                                                                                        voicevox: reading C:\Users\ass\AppData\Local\voicevox-engine\voicevox-engine\tmp893xvupc ... 62                                                                            emitting double-array: 100% |###########################################|         |                                                                                         voicevox: INFO:     Application startup complete.                                                                                                                           voicevox: INFO:     Uvicorn running on http://127.0.0.1:50021 (Press CTRL+C to quit)                                                                                        Welcome back, to speak press RIGHT_CTRL.                                                                                                                                    Connecting to VTube Studio!                                                                                                                                                 You (mic) >Authentication request sent to VTube Studio, please click allow.                                                                                                 VTube Studio connected! at port 8001                                                                                                                                        You (mic) > Are you going to work now?                                                                                                                                      Traceback (most recent call last):                                                                                                                                            File "C:\Users\ass\Desktop\pls\waifu\Src\runner.py", line 147, in <module>                                                                                                   utils.characterAi.send_message_to_process_via_websocket(transcript)                                                                                                       File "C:\Users\ass\Desktop\pls\waifu\Src\utils\characterAi.py", line 31, in send_message_to_process_via_websocket                                                            ws.send(message)                                                                                                                                                        AttributeError: 'NoneType' object has no attribute 'send'`

**Comment by TumblerWarren** [comment]
it's not transcript error, it's actually the problem of connecting to charceter.ai server

**Comment by PleaseHelpItsBroken** [comment]
> it's not transcript error, it's actually the problem of connecting to charceter.ai server

So should I wait like 15 mins before trying to speak to ensure ive waited out that timer thing?

**Comment by TumblerWarren** [comment]
Well, it will not work, I tried to fix it, but I could not. So I used another way. You can check my [project](https://github.com/TumblerWarren/Waifu), if you wanna run.
