### ISSUE TITLE
No module named pyaudio

### ISSUE THREAD

**Issue by Kazuya994** [AlizerUncaged/desktop-waifu#171]
I fixed the problem with the location of Python 310, but later on appeared this:
←[1m←[32m
You are in a virtual environment: "C:\Program Files\waifu\desktop-waifu-master\desktop-waifu-master\waifu"
←[0m
Traceback (most recent call last):
  File "C:\Program Files\waifu\desktop-waifu-master\desktop-waifu-master\waifu\Src\runner.py", line 46, in <module>
    import utils.audio
  File "C:\Program Files\waifu\desktop-waifu-master\desktop-waifu-master\waifu\Src\utils\audio.py", line 1, in <module>
    import pyaudio
ModuleNotFoundError: No module named 'pyaudio'
Presione una tecla para continuar . . .

What can I do?

**Comment by Kazuya994** [comment]
Thank you,- so much, that worked perfectly.
However, there´s still an error when connecting:

Welcome back, to speak press RIGHT_CTRL.
Connecting to VTube Studio!
You (mic) >Exception in thread Thread-3 (start_real):
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\windows_events.py", line 480, in finish_recv
    return ov.getresult()
OSError: [WinError 64] El nombre de red especificado ya no está disponible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tobav\Downloads\desktop-waifu-master\waifu\lib\site-packages\websockets\legacy\client.py", line 139, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "C:\Users\tobav\Downloads\desktop-waifu-master\waifu\lib\site-packages\websockets\legacy\http.py", line 120, in read_response
    status_line = await read_line(stream)
  File "C:\Users\tobav\Downloads\desktop-waifu-master\waifu\lib\site-packages\websockets\legacy\http.py", line 194, in read_line
    line = await stream.readline()
  File "C:\Python310\lib\asyncio\streams.py", line 525, in readline
    line = await self.readuntil(sep)
  File "C:\Python310\lib\asyncio\streams.py", line 617, in readuntil
    await self._wait_for_data('readuntil')
  File "C:\Python310\lib\asyncio\streams.py", line 502, in _wait_for_data
    await self._waiter
  File "C:\Python310\lib\asyncio\proactor_events.py", line 282, in _loop_reading
    length = fut.result()
  File "C:\Python310\lib\asyncio\windows_events.py", line 812, in _poll
    value = callback(transferred, key, ov)
  File "C:\Python310\lib\asyncio\windows_events.py", line 484, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] El nombre de red especificado ya no está disponible

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\tobav\Downloads\desktop-waifu-master\waifu\Src\utils\vtube_studio.py", line 150, in start_real
    EVENT_LOOP.run_until_complete(start())
  File "C:\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\tobav\Downloads\desktop-waifu-master\waifu\Src\utils\vtube_studio.py", line 111, in start
    await VTS.connect()
  File "C:\Users\tobav\Downloads\desktop-waifu-master\waifu\lib\site-packages\pyvts\vts.py", line 70, in connect
    self.websocket = await websockets.connect(
  File "C:\Users\tobav\Downloads\desktop-waifu-master\waifu\lib\site-packages\websockets\legacy\client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "C:\Users\tobav\Downloads\desktop-waifu-master\waifu\lib\site-packages\websockets\legacy\client.py", line 662, in __await_impl__
    await protocol.handshake(
  File "C:\Users\tobav\Downloads\desktop-waifu-master\waifu\lib\site-packages\websockets\legacy\client.py", line 323, in handshake
    status_code, response_headers = await self.read_http_response()
  File "C:\Users\tobav\Downloads\desktop-waifu-master\waifu\lib\site-packages\websockets\legacy\client.py", line 145, in read_http_response
    raise InvalidMessage("did not receive a valid HTTP response") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response
node js: C:\Users\tobav\Downloads\desktop-waifu-master\character_ai\chat.js:11
node js:         const ai = continueBody.participants.find(
node js:                                              ^
node js:
node js: TypeError: Cannot read properties of undefined (reading 'find')
node js:     at new Chat (C:\Users\tobav\Downloads\desktop-waifu-master\character_ai\chat.js:11:46)
node js:     at Client.createOrContinueChat (C:\Users\tobav\Downloads\desktop-waifu-master\character_ai\client.js:164:20)
node js:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
node js:     at async main (C:\Users\tobav\Downloads\desktop-waifu-master\character_ai\runner.js:57:26)
node js:
node js: Node.js v18.17.1

**Comment by misaki1301** [comment]
it appears that not find that something related to the node wrapper api of character.ai, maybe updating manually the library can works

**Comment by ajaxashborne** [comment]
(waifu) D:\desktop-waifu-master\desktop-waifu-master\waifu\Scripts>pip install pyaudio
Fatal error in launcher: Unable to create process using '"C:\Users\alzco\source\repos\desktop-waifu\waifu\Scripts\python.exe"  "D:\desktop-waifu-master\desktop-waifu-master\waifu\Scripts\pip.exe" install pyaudio': The system cannot find the file specified.


what to do know i am confused
