### ISSUE TITLE
I press left CTRL and nothing happen.

### ISSUE THREAD

**Issue by TheFoo0L** [AlizerUncaged/desktop-waifu#173]
←[1m←[32m
You are in a virtual environment: "C:\Users\LEFI\Downloads\desktop-waifu-master\desktop-waifu-master\waifu"
←[0m
Exception in thread Thread-1 (<lambda>):
Traceback (most recent call last):
  File "C:\Users\LEFI\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\LEFI\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\LEFI\Downloads\desktop-waifu-master\desktop-waifu-master\waifu\Src\utils\characterAi.py", line 85, in <lambda>
    t = threading.Thread(target=lambda: loop.run_until_complete(start()))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LEFI\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\LEFI\Downloads\desktop-waifu-master\desktop-waifu-master\waifu\Src\utils\characterAi.py", line 58, in start
    process = await asyncio.create_subprocess_exec(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LEFI\AppData\Local\Programs\Python\Python311\Lib\asyncio\subprocess.py", line 221, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LEFI\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1694, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LEFI\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 399, in _make_subprocess_transport
    transp = _WindowsSubprocessTransport(self, protocol, args, shell,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LEFI\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "C:\Users\LEFI\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 921, in _start
    self._proc = windows_utils.Popen(
                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LEFI\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_utils.py", line 153, in __init__
    super().__init__(args, stdin=stdin_rfd, stdout=stdout_wfd,
  File "C:\Users\LEFI\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\LEFI\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
Welcome back, to speak press RIGHT_CTRL.
Connecting to VTube Studio!
You (mic) >Authentication request sent to VTube Studio, please click allow.
VTube Studio connected! at port 8001

**Comment by AxelZorgal** [comment]
You just have to change the keyboard language on your computer go to settings, devices, writing, advanced keyboard settings and in the area of ​​replace input method you change it to English United States save and close everything and open the vtube studio and the start.exe
