### ISSUE TITLE
You are in a virtual environment: IndexError: list index out of rang

### ISSUE THREAD

**Issue by mr-fool** [AlizerUncaged/desktop-waifu#184]
You are in a virtual environment: "C:\Users\hetzer\Documents\waifu\desktop-waifu-master\waifu"

(134.7 MB)
Unzipping...(134.7 MB) Already exists!
Unzipping...Traceback (most recent call last):
  File "C:\Users\hetzer\Documents\waifu\desktop-waifu-master\waifu\Src\runner.py", line 60, in <module>
    import utils.elevenlabs
  File "C:\Users\hetzer\Documents\waifu\desktop-waifu-master\waifu\Src\utils\elevenlabs.py", line 13, in <module>
    ELEVENLABS_VOICE = ELEVENLABS_CLIENT.get_voices_by_name(env_voice)[0]
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
node js
Press any key to continue . . .

**Comment by ChrisDstryder** [comment]
"I have the same problem as you, did you manage to find a solution on how to fix it?"

**Comment by mr-fool** [comment]
I think I use chatgpt to fix it but it is a long time ago. I think you are better off using https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI

**Comment by zimavi** [comment]
Can you show your .env file?
