### ISSUE TITLE
error message with send?

### ISSUE THREAD

**Issue by MODOMison** [AlizerUncaged/desktop-waifu#189]
Welcome back, to speak press RIGHT_CTRL.
Connecting to VTube Studio!
You (mic) >Authentication request sent to VTube Studio, please click allow.
VTube Studio connected! at port 8001
You (mic) > Hello?
Traceback (most recent call last):
  File "C:\Users\matto\Downloads\desktop-waifu-master\desktop-waifu-master\waifu\Src\runner.py", line 147, in <module>
    utils.characterAi.send_message_to_process_via_websocket(transcript)
  File "C:\Users\matto\Downloads\desktop-waifu-master\desktop-waifu-master\waifu\Src\utils\characterAi.py", line 31, in send_message_to_process_via_websocket
    ws.send(message)
    ^^^^^^^
AttributeError: 'NoneType' object has no attribute 'send'

**Comment by Jaimeno** [comment]
I need help with that too

**Comment by Pledoge** [comment]
Oh, I know the reason. That is because the speaker's name in env file are different from your elevenlabs'.
