### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'send'

### ISSUE THREAD

**Issue by junkeith** [AlizerUncaged/desktop-waifu#243]
I saw that it is a reoccurring problemm for months now, did anyone manage to fix it?

Traceback (most recent call last):
  File "C:\Users\Desktop\desktop-waifu-master\waifu\Src\runner.py", line 147, in <module>
    utils.characterAi.send_message_to_process_via_websocket(transcript)
  File "C:\Users\Desktop\desktop-waifu-master\waifu\Src\utils\characterAi.py", line 31, in send_message_to_process_via_websocket
    ws.send(message)
    
AttributeError: 'NoneType' object has no attribute 'send'
node js
Press any key to continue . . .

**Comment by KittensScythe** [comment]
Getting the same issue, did you end up finding a solution?

**Comment by kraxius** [comment]
ı have same problem too
