### ISSUE TITLE
No module named 'pyaudio'

### ISSUE THREAD

**Issue by AlisonX84** [AlizerUncaged/desktop-waifu#268]
Traceback (most recent call last):
  File "C:\Users\trant\Downloads\desktop-waifu-master\waifu\Src\runner.py", line 46, in <module>
    import utils.audio
  File "C:\Users\trant\Downloads\desktop-waifu-master\waifu\Src\utils\audio.py", line 1, in <module>
    import pyaudio
ModuleNotFoundError: No module named 'pyaudio'
Press any key to continue . . .

**Comment by Xothika** [comment]
You have to manually install this. 

**First** start up  waifu/scripts/activate.bat
**Then** type pip install pyaudio  


[Hope this helps]

**Comment by AlisonX84** [comment]
(waifu) C:\Users\trant\Downloads\desktop-waifu-master\waifu\Scripts>pip install pyaudio
Fatal error in launcher: Unable to create process using '"C:\Users\alzco\source\repos\desktop-waifu\waifu\Scripts\python.exe"  "C:\Users\trant\Downloads\desktop-waifu-master\waifu\Scripts\pip.exe" install pyaudio': The system cannot find the file specified.

**Comment by AlisonX84** [comment]
Even though I used Terminal
C:\Users\trant> pip install pyaudio
Requirement already satisfied: pyaudio in c:\users\trant\appdata\local\programs\python\python310\lib\site-packages (0.2.14)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
