### ISSUE TITLE
Websocket Closed

### ISSUE THREAD

**Issue by NeoStormm** [AlizerUncaged/desktop-waifu#27]
Right after I say something into the mic I get this.

Traceback (most recent call last):
  File "C:\Users\Neostorm\Documents\fix default program\desktop-waifu-master\waifu\Src\runner.py", line 147, in <module>    utils.characterAi.send_message_to_process_via_websocket(transcript)
  File "C:\Users\Neostorm\Documents\fix default program\desktop-waifu-master\waifu\Src\utils\characterAi.py", line 31, in send_message_to_process_via_websocket
    ws.send(message)
  File "C:\Users\Neostorm\Documents\fix default program\desktop-waifu-master\waifu\Lib\site-packages\websocket\_app.py", line 240, in send
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

**Comment by Sylensar** [comment]
@NeoStormm Did you ever solve this? If so how. Thanks in advanced.

**Comment by DarkUrine** [comment]
@NeoStormm I would also like to know because it isn't being addressed
