### ISSUE TITLE
Traceback (most recent call last):   File "C:\Users\Acer\Documents\desktop-waifu-master\waifu\Src\runner.py", line 1, in <module>     from colorama import * ModuleNotFoundError: No module named 'colorama' Press any key to continue . . .

### ISSUE THREAD

**Issue by alfariziadekarlin** [AlizerUncaged/desktop-waifu#277]
Traceback (most recent call last):
  File "C:\Users\Acer\Documents\desktop-waifu-master\waifu\Src\runner.py", line 1, in <module>
    from colorama import *
ModuleNotFoundError: No module named 'colorama'
Press any key to continue . . .

**Comment by AuthourAkson** [comment]
Find the activate.bat in scripts folder, then enter in and pip install it

**Comment by Lukebox045** [comment]
> colorama

what we need to input ?
