### ISSUE TITLE
NameError: name 'ElevenLabsUser' is not defined node js

### ISSUE THREAD

**Issue by Falkone35** [AlizerUncaged/desktop-waifu#300]
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\desktop-waifu-master\waifu\Src\runner.py", line 60, in <module>
    import utils.elevenlabs
  File "C:\Users\Admin\Desktop\desktop-waifu-master\waifu\Src\utils\elevenlabs.py", line 6, in <module>
    ELEVENLABS_CLIENT = ElevenLabsUser(os.environ.get("ELEVENLABS_KEY"))
NameError: name 'ElevenLabsUser' is not defined
node js
Press any key . . .
-------------------------------------------------------------------------------------------------------------
someone have a solution for this problem didn't find anything about it

**Comment by StephenChen2016** [comment]
i have same problem

**Comment by StephenChen2016** [comment]
pip install elevenlabslib==0.2.6 i solve it hhh

**Comment by leotakig** [comment]
I did it but it didn't work. Should I install in some specific folder?
