### ISSUE TITLE
Cromium Issue

### ISSUE THREAD

**Issue by Sylensar** [AlizerUncaged/desktop-waifu#32]
Im having the Cromium error at the start and Im also getting this once I talk into the mic

**Welcome back, to speak press RIGHT_SHIFT, RIGHT_CTRL at the same time.
Connecting to VTube Studio!
You (mic) >Authentication request sent to VTube Studio, please click allow.
VTube Studio connected! at port 8001
You (mic) > you
Traceback (most recent call last):
  File "D:\ainy3\desktop-waifu-master\waifu\Src\runner.py", line 147, in <module>
    utils.characterAi.send_message_to_process_via_websocket(transcript)
  File "D:\ainy3\desktop-waifu-master\waifu\Src\utils\characterAi.py", line 31, in send_message_to_process_via_websocket
    ws.send(message)
  File "D:\ainy3\desktop-waifu-master\waifu\lib\site-packages\websocket\_app.py", line 240, in send
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
node js
Press any key to continue . . .**

**Comment by MMD08** [comment]
have you ever fix this error?
