### ISSUE TITLE
May I humbly ask for your assistance? :>

### ISSUE THREAD

**Issue by aidevlock** [AlizerUncaged/desktop-waifu#35]
No Python at 'C:\Users\flandre-real\AppData\Local\Programs\Python\Python310\python.exe'
Press any key to continue . . .

**Comment by aidevlock** [comment]
You are in a virtual environment: ./waifu

Traceback (most recent call last):
  File "C:\waifu\desktop-waifu-master\waifu\Src\runner.py", line 46, in <module>
    import utils.audio
  File "C:\waifu\desktop-waifu-master\waifu\Src\utils\audio.py", line 1, in <module>
    import pyaudio
ModuleNotFoundError: No module named 'pyaudio'
Press any key to continue . . .
