### ISSUE TITLE
random stops

### ISSUE THREAD

**Issue by motormonster** [AlizerUncaged/desktop-waifu#40]
response: {"force_login":true}
node js: C:\Users\mjcar\OneDrive\Desktop\desktop-waifu-master\character_ai\chat.js:71
node js:             for (let i = 0; i < replies.length; i++) {
node js:                                         ^
node js:
node js: TypeError: Cannot read properties of undefined (reading 'length')
node js:     at Chat.sendAndAwaitResponse (C:\Users\mjcar\OneDrive\Desktop\desktop-waifu-master\character_ai\chat.js:71:41)
node js:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
node js:     at async WebSocket.<anonymous> (C:\Users\mjcar\OneDrive\Desktop\desktop-waifu-master\character_ai\runner.js:40:26)
node js:
node js: Node.js v20.0.0

not even sure what to make of this. any help would be amazing! I've gotten this far with stuff breaking.

**Comment by DarkUrine** [comment]
Did you ever find a fix to this?
