### ISSUE TITLE
Connection is already closed error

### ISSUE THREAD

**Issue by Wheatlyp2** [AlizerUncaged/desktop-waifu#42]
You (mic) >Authentication request sent to VTube Studio, please click allow.
VTube Studio connected! at port 8001
You (mic) > Hello, introduce yourself.
Traceback (most recent call last):
  File "E:\ai vtuber\desktop-waifu-master\waifu\Src\runner.py", line 147, in <module>
    utils.characterAi.send_message_to_process_via_websocket(transcript)
  File "E:\ai vtuber\desktop-waifu-master\waifu\Src\utils\characterAi.py", line 31, in send_message_to_process_via_websocket
    ws.send(message)
  File "E:\ai vtuber\desktop-waifu-master\waifu\Lib\site-packages\websocket\_app.py", line 240, in send
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
node js

**Comment by wetzernutz** [comment]
you have to click 'allow' to allow the connection to Vtube studio to be established before sending any messages.

**Comment by MMD08** [comment]
have you fix the problem?, i have the same error even after i click allow on vtube studio

**Comment by DarkUrine** [comment]
I also have this issue even after pressing allow.
