### ISSUE TITLE
some error i cant seem to fix.

### ISSUE THREAD

**Issue by motormonster** [AlizerUncaged/desktop-waifu#45]
hey. so @AlizerUncaged im currently trying to fix this thing up a bit sense it seems everyone is having issues with a lot of it and I cant seem to fix this error without needing to remake the whole chat.js file. here's the error below, if you or anyone could help that would be amazing!

node js: response: {"force_login":true}
node js: C:\Users\mjcar\OneDrive\Desktop\desktop-waifu-master\character_ai\chat.js:71
node js:             for (let i = 0; i < replies.length; i++) {
node js:                                         ^
node js:
node js: TypeError: Cannot read properties of undefined (reading 'length')
node js:     at Chat.sendAndAwaitResponse (C:\Users\mjcar\OneDrive\Desktop\desktop-waifu-master\character_ai\chat.js:71:41)
node js:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
node js:     at async WebSocket.<anonymous> (C:\Users\mjcar\OneDrive\Desktop\desktop-waifu-master\character_ai\runner.js:40:26)
node js:
node js: Node.js v20.0.0

**Comment by chancla2** [comment]
hi, any news about it?

**Comment by motormonster** [comment]
sadly no, i haven't really been able to fix that bit of code, ig it breaks thinking it doesn't know what 'length' is.

**Comment by Spy4070D** [comment]
I believe this error is likely related to the limited free messages for guest users on Character.AI.
