### ISSUE TITLE
"Connection is already closed" and yes i have press allow on vtube studio

### ISSUE THREAD

**Issue by MMD08** [AlizerUncaged/desktop-waifu#53]
Traceback (most recent call last):
  File "C:\C.ai\desktop-waifu-master\waifu\Src\runner.py", line 147, in <module>
    utils.characterAi.send_message_to_process_via_websocket(transcript)
  File "C:\C.ai\desktop-waifu-master\waifu\Src\utils\characterAi.py", line 31, in send_message_to_process_via_websocket
    ws.send(message)
  File "C:\C.ai\desktop-waifu-master\waifu\Lib\site-packages\websocket\_app.py", line 240, in send
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
node js

**Comment by DarkUrine** [comment]
Man it would be nice to actually get an answer on this one. Same issue here

**Comment by Sylensar** [comment]
You might have to change some coding. I got it working some days ago and been good ever since. I have to see what line I changed

**Comment by DarkUrine** [comment]
@Sylensar Yeah man if you could see what you changed to make it work and send it here that would be amazing! Or better yet send a comment over to the other issue post I posted recently so that everyone having this issue might be able to fix it! Thanks in advance.

**Comment by goodiesohhi** [comment]
Uhhhh. Hello? Any update on this?
