### ISSUE TITLE
Problem with generating Voice

### ISSUE THREAD

**Issue by Tamerlan93PL** [AlizerUncaged/desktop-waifu#75]
Program properly recognize what I said. But couldnt generate any answer text/audio. What is the problem. Below is what I received.

------------------------------------------------------------------------------------------------------------
You (mic) > Hello, what's your name?
Traceback (most recent call last):
  File "C:\Users\Xana\Downloads\desktop-waifu-master\waifu\Src\runner py", line 147, in <module>
    utils.characterAi.send_message_to_process_via_websocket(transcript)
  File "C:\Users\Xana\Downloads\desktop-waifu-master\waifu\Src\utils\characterAi py", line 31, in send_message_to_process_via_websocket
    ws.send(message)
AttributeError: 'NoneType' object has no attribute 'send'
------------------------------------------------------------------------------------------------------------

**Comment by Tamerlan93PL** [comment]
I read other threads and I solved my problem by installing Node.js but now I have diffrent problem check this out. Damn why this works so good for others. 
----------------------------------------------------------------------------------------------------------------------
You (mic) > Hello.
node js: Unable to send message.
node js: CharacterAI is still fetching character data!
node js: If it's taking far too long please submit an issue.

**Comment by kiranim999** [comment]
yeah same here i got it all to work just to face this, did you solve it yet or did you give up?
