### ISSUE TITLE
es funktioniert nicht ich kann keine eingabe machen bitte um rat

### ISSUE THREAD

**Issue by Xentox99** [AlizerUncaged/desktop-waifu#88]
←[1m←[32m
You are in a virtual environment: "C:\waifu\desktop-waifu-master\desktop-waifu-master\waifu"
←[0m
Exception in thread Thread-1 (<lambda>):
Traceback (most recent call last):
  File "C:\Python310\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python310\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\waifu\desktop-waifu-master\desktop-waifu-master\waifu\Src\utils\characterAi.py", line 85, in <lambda>
    t = threading.Thread(target=lambda: loop.run_until_complete(start()))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python310\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\waifu\desktop-waifu-master\desktop-waifu-master\waifu\Src\utils\characterAi.py", line 58, in start
    process = await asyncio.create_subprocess_exec(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python310\Lib\asyncio\subprocess.py", line 221, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python310\Lib\asyncio\base_events.py", line 1694, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python310\Lib\asyncio\windows_events.py", line 399, in _make_subprocess_transport
    transp = _WindowsSubprocessTransport(self, protocol, args, shell,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python310\Lib\asyncio\base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "C:\Python310\Lib\asyncio\windows_events.py", line 921, in _start
    self._proc = windows_utils.Popen(
                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python310\Lib\asyncio\windows_utils.py", line 153, in __init__
    super().__init__(args, stdin=stdin_rfd, stdout=stdout_wfd,
  File "C:\Python310\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
Welcome back, to speak press RIGHT_CTRL.
Connecting to VTube Studio!
You (mic) >Authentication request sent to VTube Studio, please click allow.
VTube Studio connected! at port 8001

**Comment by P4bl0M** [comment]
geh in waiffu -> Src -> utils 
dann öffne hotkeys.py
und bei KEY schreibst du einfache eine andere taste z.B. +
